### ISSUE TITLE
运行run.sh在stage 4时报错

### ISSUE THREAD

**Issue by voidpointz** [alibaba-damo-academy/FunCodec#41]
报错信息如下所示：
run.pl: job failed, log is in /mnt/d/Work/FunCodec/egs/LibriTTS/text2speech_laura/dump/libritts/test-other/codecs//logdir/inference.1.log
cat: '/mnt/d/Work/FunCodec/egs/LibriTTS/text2speech_laura/dump/libritts/test-other/codecs//logdir/output.*/codecs.txt': No such file or directory
Codes are saved to /mnt/d/Work/FunCodec/egs/LibriTTS/text2speech_laura/dump/libritts/test-other/codecs//logdir/output.*/codecs.txt and collected to /mnt/d/Work/FunCodec/egs/LibriTTS/text2speech_laura/dump/libritts/test-other/codecs//codecs.txt.
codec scp files are collected into /mnt/d/Work/FunCodec/egs/LibriTTS/text2speech_laura/dump/libritts/test-other/codec_token.scp

log里看起来是路径错误，但是前几步，stage1到3都没错：

2024-04-15 15:52:57,508 (codec_inference:233) INFO: param_dict: None
Traceback (most recent call last):
  File "/home/zz/anaconda3/envs/Laura/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zz/anaconda3/envs/Laura/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zz/work/FunCodec/funcodec/bin/codec_inference.py", line 584, in <module>
    main()
  File "/home/zz/work/FunCodec/funcodec/bin/codec_inference.py", line 580, in main
    inference(**kwargs)
  File "/home/zz/work/FunCodec/funcodec/bin/codec_inference.py", line 425, in inference
    return inference_pipeline(data_path_and_name_and_type, raw_inputs=None)
  File "/home/zz/work/FunCodec/funcodec/bin/codec_inference.py", line 313, in _forward
    for keys, batch in loader:
  File "/home/zz/anaconda3/envs/Laura/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/zz/anaconda3/envs/Laura/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/home/zz/anaconda3/envs/Laura/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/home/zz/anaconda3/envs/Laura/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zz/anaconda3/envs/Laura/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zz/anaconda3/envs/Laura/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/zz/work/FunCodec/funcodec/datasets/iterable_dataset.py", line 260, in __iter__
    array = func(value)
  File "/home/zz/work/FunCodec/funcodec/datasets/iterable_dataset.py", line 28, in load_kaldi
    retval = kaldiio.load_mat(input)
  File "/home/zz/anaconda3/envs/Laura/lib/python3.9/site-packages/kaldiio/matio.py", line 239, in load_mat
    with open_like_kaldi(ark, "rb") as fd:
  File "/home/zz/anaconda3/envs/Laura/lib/python3.9/site-packages/kaldiio/utils.py", line 207, in open_like_kaldi
    return io.open(name, mode, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/libritts/train/arks/wav.00.ark'

**Comment by a897456** [comment]
stage3，有没有遇到这个错误：
  File "/mnt/e/000/FunCodec-master/funcodec/models/codec_basic.py", line 66, in forward
    mel_output = torch.matmul(self.mel_basis, power_spec)
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x513 and 4x513)
不知道怎么解决了

**Comment by voidpointz** [comment]
> stage3，有没有遇到这个错误： File "/mnt/e/000/FunCodec-master/funcodec/models/codec_basic.py", line 66, in forward mel_output = torch.matmul(self.mel_basis, power_spec)
> 
> # RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x513 and 4x513)
> 不知道怎么解决了

我这里没碰到问题，看起来像库的问题，我用的是python3.9

**Comment by yxlu-0102** [comment]
这里是不是因为 codec/dump 下面是 LibriTTS，但 text2speech_laura/dump 下面是 libritts
