### ISSUE TITLE
Stage 3

### ISSUE THREAD

**Issue by a897456** [alibaba-damo-academy/FunCodec#42]
/home/rian0532/anaconda3/envs/py39Ubuntu/lib/python3.9/site-packages/torch/nn/modules/conv.py:306: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv1d(input, weight, bias, self.stride,
[DESKTOP-PQV8NDO] 2024-04-16 14:56:40,650 (codec_basic:648) INFO: Will update discriminator: forward_step=0, disc_loss=2.0000, gen_loss=0.0000
Traceback (most recent call last):
  File "/home/rian0532/anaconda3/envs/py39Ubuntu/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rian0532/anaconda3/envs/py39Ubuntu/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/e/000/FunCodec-master/funcodec/bin/codec_train.py", line 48, in <module>
    main(args=args)
  File "/mnt/e/000/FunCodec-master/funcodec/bin/codec_train.py", line 23, in main
    GANSpeechCodecTask.main(args=args, cmd=cmd)
  File "/mnt/e/000/FunCodec-master/funcodec/tasks/abs_task.py", line 1130, in main
    cls.main_worker(args)
  File "/mnt/e/000/FunCodec-master/funcodec/tasks/abs_task.py", line 1431, in main_worker
    cls.trainer.run(
  File "/mnt/e/000/FunCodec-master/funcodec/train/trainer.py", line 308, in run
    all_steps_are_invalid, max_update_stop = cls.train_one_epoch(
  File "/mnt/e/000/FunCodec-master/funcodec/train/gan_trainer.py", line 185, in train_one_epoch
    retval = model(turn == "generator", batch)
  File "/home/rian0532/anaconda3/envs/py39Ubuntu/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/rian0532/anaconda3/envs/py39Ubuntu/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/e/000/FunCodec-master/funcodec/models/codec_basic.py", line 324, in forward
    return self._forward_generator(
  File "/mnt/e/000/FunCodec-master/funcodec/models/codec_basic.py", line 528, in _forward_generator
    orig_mel, recon_mel = map(mel_transform, (orig_speech, recon_speech))
  File "/home/rian0532/anaconda3/envs/py39Ubuntu/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/rian0532/anaconda3/envs/py39Ubuntu/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/e/000/FunCodec-master/funcodec/models/codec_basic.py", line 66, in forward
    mel_output = torch.matmul(self.mel_basis, power_spec)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x513 and 4x513)

**Comment by a897456** [comment]
我觉得这个错误，不应该出现，可能哪里出现了错误，但是我又找不出，所以请求帮助。

**Comment by ZhihaoDU** [comment]
确实很奇怪，不应该出现这个错误。是不是librosa或者torch的版本不对呢？我这边是torch==1.12，librosa==0.10.0.post2

**Comment by butterfly-cloud** [comment]
同样问题 torch2.2.0+cu121

**Comment by a897456** [comment]
https://github.com/modelscope/FunCodec/blob/3435d870126a48fe61a87fac1af3b6530be388ea/funcodec/models/codec_basic.py#L57-L64
add `return_complex=False` will be OK
