### ISSUE TITLE
Getting error while testing LauraTTS

### ISSUE THREAD

**Issue by rishikksh20** [alibaba-damo-academy/FunCodec#6]
Hi @ZhihaoDU while running LauraTTS from `egs/LibriTTS/text2speech_laura` README I am getting error which described below.

When using `ModelScope`, getting following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rishikesh/.local/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/home/rishikesh/.local/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/home/rishikesh/.local/lib/python3.10/site-packages/modelscope/utils/registry.py", line 198, in build_from_cfg
    raise KeyError(
KeyError: 'laura-codec-tts-inference is not in the pipelines registry group text-to-speech. Please make sure the correct version of ModelScope library is used.'
```

~~While running `bash` command, getting following error:~~

```
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/rishikesh/code/FunCodec/funcodec/bin/text2audio_inference.py", line 561, in <module>
    main()
  File "/home/rishikesh/code/FunCodec/funcodec/bin/text2audio_inference.py", line 557, in main
    inference(**kwargs)
  File "/home/rishikesh/code/FunCodec/funcodec/bin/text2audio_inference.py", line 381, in inference
    inference_pipeline = inference_func(
  File "/home/rishikesh/code/FunCodec/funcodec/bin/text2audio_inference.py", line 287, in inference_func
    my_model = Text2Audio.from_pretrained(
  File "/home/rishikesh/code/FunCodec/funcodec/bin/text2audio_inference.py", line 227, in from_pretrained
    return Text2Audio(**kwargs)
  File "/home/rishikesh/code/FunCodec/funcodec/bin/text2audio_inference.py", line 53, in __init__
    model, model_args = Text2AudioGenTask.build_model_from_file(
  File "/home/rishikesh/code/FunCodec/funcodec/tasks/abs_task.py", line 1928, in build_model_from_file
    model = cls.build_model(args)
  File "/home/rishikesh/code/FunCodec/funcodec/tasks/text2audio_generation.py", line 206, in build_model
    if args.text_encoder is not None:
AttributeError: 'Namespace' object has no attribute 'text_encoder'
```

**FYI :** **Bash issue is ressolved**

**Comment by ZhihaoDU** [comment]
Thanks for your error reporting. `ModelScope` approach requires the latest version of ModelScope lib, which is at the internal test stage currently. I believe this version will release at the end of December, you can try `ModelScope` approach again in Jan. 2023. I sorry to say, currently, only `bash` approach is supported.
